server:
  port: 8761   #服务端口号

eureka:
  instance:
    hostname: localhost  #服务主机
  client:
    #当前的Eureka服务是单机版的
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  security:
    user:
      name: root
      password: root