#指定Eureka服务地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/,http://root:root@localhost:8762/eureka/
    registry-fetch-interval-seconds: 30   #每隔30秒向Eureka获取更新一次本地注册表

#指定服务的名称
spring:
  application:
    name: CUSTOMER
#指定具体服务的负载均衡策略
SEARCH:    #编写服务名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule


