server:
  port: 8762   #服务端口号

eureka:
  instance:
    hostname: localhost  #服务主机
    lease-renewal-interval-in-seconds: 30   #心跳的间隔
    lease-expiration-duration-in-seconds: 90    #多久没发送，就认为你宕机了
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
  server:
    enable-self-preservation: true   #开启自我保护机制

spring:
  security:
    user:
      name: root
      password: root
  application:
    name: EUREKA-04